### ISSUE TITLE
Possible to compute for Polygons With holes?

### ISSUE THREAD

**Issue by rukemn** [twak/campskeleton#11]
I was looking at your implementation, thanks for that.

When trying to run the implementation for a polygon with holes, the was an "Error in input". 
As described in the paper you referenced, the algorithm is supposed to handle those situations, given that the edges of the holes are oriented such that the polygon is to the left of the edge ( i.e. holes are clockwise, the shell is counterclockwise).

I simply adapted your example by adding the needed cornes and edges to `loop1`.

Is there anything I am missing or does you implementation simply not work for polygons with holes?

**Comment by twak** [comment]
yes it works with holes, they have to defined as a separate loop in a backwards direction. thanks for closing!
