### ISSUE TITLE
Get bones, edges and branches separately

### ISSUE THREAD

**Issue by micycle1** [twak/campskeleton#14]
Is it possible to get these three things separately from `skeleton.output`?

Atm I'm using `skeleton.output.edges.map.values()` and testing whether the coordinates `start` and `end` for each edge are contained in the set of vertices (corners) to determine the status of the edge — is there a direct way?

![image](https://user-images.githubusercontent.com/9304234/113320402-621dac80-930a-11eb-94ac-e79f3bb613a6.png)
(edges: purple; bones: black; branches: pink)

**Comment by twak** [comment]
I think this is unlikely - from the algorithm's perspective, all these things are the same. For example, if you pick a black "bone" (I guess you call them) in your image, it's possible to draw a polygon which starts from that offset, but with your black bone as a pink "branch". 

Yes, I would suggest filtering as you do as a post process step. Look at Output.SharedEdge - if the Face on one side is null, it is a purple "edge". Then the next and previous shared edges should be pink "branches" and everything else is a "bone"?
