### ISSUE TITLE
How to build a roof like this in a reasonable way?

### ISSUE THREAD

**Issue by Elliotloststh** [twak/campskeleton#15]
I want to build roof like 
![image](https://user-images.githubusercontent.com/33218005/116382680-c0c24180-a848-11eb-8864-6f27a0b0d106.png)

each edge will produce two Face result since there are two different angle section.
how can i generate it using apis in a reasonable way?

**Comment by twak** [comment]
hey, did you figure out how to do this? It's probably quite difficult to ensure that geometry like this is reliably generated at scale!
