### ISSUE TITLE
Jitpack build issue with jutils dependency

### ISSUE THREAD

**Issue by micycle1** [twak/campskeleton#16]
I recently had a few projects that rely on camp-skeleton (master branch) fail to build.
After looking into it, I've found it's an issue on jitpack with the current master version of jutils.

campskeleton has a dependency on jutils version `master-SNAPSHOT`; this label currently points to `master-198bbef5f6-1`, and this is currently giving problems:

Go to https://jitpack.io/com/github/twak/jutils/master-198bbef5f6-1/ and we see the error:

> File not found. Build ok

**Comment by twak** [comment]
Which is strange because the label is here: https://jitpack.io/com/github/twak/jutils/

@[Gustl22](https://github.com/Gustl22) Any ideas?

![image](https://user-images.githubusercontent.com/127402/166438256-29d4c58c-4b2b-4baa-bab9-85d81db55bdc.png)

**Comment by micycle1** [comment]
Push a new version of jutils on the master branch, which will get jitpack to rebuild it hopefully with the files present!

**Comment by twak** [comment]
I clicked a button in jitpack...let's see if it builds. Suspecting I should abandon jitpack if it causes these issues :(

**Comment by twak** [comment]
fixed now. will remove jitpack when I (eventually) get around to starting up intellij again...

**Comment by Gustl22** [comment]
Sorry I couldn't help here. Unfortunately I didn't work with Java / Maven in years now :/
