### ISSUE TITLE
Everything's fine

### ISSUE THREAD

**Issue by frankiezafe** [twak/campskeleton#7]
Hello, 

thanks a lot once again for sharing your implementation.
![_066](https://user-images.githubusercontent.com/3447074/43350268-1afcc64a-9206-11e8-9719-6476de2ded53.png) (just to shows that it is running smoothly on linux)

It seems that you have chosen to avoid "split events" by reducing the length of the median when it crosses an edge. I like the approach.
![_067](https://user-images.githubusercontent.com/3447074/43350423-39a64854-9207-11e8-948e-693a6b447f5f.png)

I've worked on a c++ implementation of straight skeletons, but I had logical issues when solving the intersections. I guess you solved it in your code :)
I'll let you know as soon I'm starting to work again on my code.

All the best,

francois z.

**Comment by twak** [comment]
Glad the code worked for you! Yes, linux here too. 

The intersection events are difficult; but it'll be nice to have a c++ implementation.
