### ISSUE TITLE
Could not resolve dependecies on maven install.

### ISSUE THREAD

**Issue by Gustl22** [twak/campskeleton#8]
If I run `mvn install` I get these message:

The following artifacts could not be resolved: 
org.twak.utils:utils:jar:0.0.1-SNAPSHOT, 
org.twak.campskeleton:campskeleton:jar:0.0.1-SNAPSHOT

I wonder, because in the past it worked for me.
This happens with other projects like `siteplan` or `chordatlas`.

All other dependencies are fetched with maven correctly.

**Comment by twak** [comment]
try running `mvn install` for [jutils](https://github.com/twak/jutils)? Sorry there's no public mvn repo and you have to check it out yourself!

**Comment by Gustl22** [comment]
I will start a PR with Jitpack dependencies, if you don't mind:

[![](https://jitpack.io/v/twak/jutils.svg)](https://jitpack.io/#twak/jutils)

```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependency>
	    <groupId>com.github.twak</groupId>
	    <artifactId>jutils</artifactId>
	    <version>master-SNAPSHOT</version>
	</dependency>
```

**Comment by twak** [comment]
I'm not a maven expert - is there a way for me to easily switch between jitpack and local versions of these repositories?

During development I'm usually touching as much code in jutils as campskeleton and the simplest way to set up a dev environment is to import the 5+ repos as mvn projects with "local dependencies"  enabled in the IDE.

**Comment by Gustl22** [comment]
I started the PR in #10 and added profiles, so you can use your old workflow.
I recommend testing it before merging and give feedback, if it works for you.

**Comment by Gustl22** [comment]
Fixed via #10.

**Comment by Gustl22** [comment]
@twak only a hint: I think it's more confusing than helping to add ˋstableˋ branch which is at least more updated than master.
Also master most commonly is the branch to be displayed and represents current stable state of library. So there's no need for ˋstableˋ branches, as stable states are saved as the released packages.
Just before release simply can increase to next version and commit, so it will be part of the release.

Its more common to use development or feature branches and merge them to master, if they seem stable.

**Comment by twak** [comment]
The goal for the stable branch is to be less commonly updated than master, but (at least) to guarantee to build the toolchain (jutils, campskeleton, siteplan, and chordatlas). 

Whether we identify releases with tags or branches seems arbitrary - both have the same result.

I will code on master and release on stable - the default branch is set to stable to suggest this. 
I realise that this isn't the traditional git convention, but while this is a one-man project (with most of the use and the coding being by me) it seems pragmatic. This is code is primarily for research - I believe in moving fast and breaking things (on master)!

**Comment by Gustl22** [comment]
Thanks for explanation, of course it's every ones own descision. Only noticed the unconventional workflow ;D
At least thanks for merging my PRs, and be able to use your awesome lib.
